# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Lab Manual, FEMTO Neuro Group

theme:
  name: material

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:

  - 'Welcome': 'index.md'

  - 'About this manual': 
    - 'Manual metadata' : 'about-this-manual/manual-metadata.md'
    - 'Why we use a lab manual' : 'about-this-manual/why-we-use-a-lab-manual.md'
    - 'How to update the manual' : 'about-this-manual/how-to-update-the-manual.md' 
    - 'Abbreviations': 'about-this-manual/abbreviations.md'

  - 'About the lab':
    - 'Lab mission & focus': 'about-the-lab/lab-mission-and-focus.md'
    - 'Lab philosophy/values' : 'about-the-lab/lab-philosophy-values.md'
    - 'Lab history' : 'about-the-lab/lab-history.md'
    - 'Lab space' : 'about-the-lab/lab-space.md'
    - 'About the team, dept and institute': 'about-the-lab/about-the-team-dept-and-institute.md'
    - 'About our operating institutions' : 'about-the-lab/about-our-operating-institutions.md'
    - 'Ethical code of conduct': 'about-the-lab/ethical-code-of-conduct.md'

  - 'Becoming a lab member': 
    - 'ZRR application' : 'becoming-a-lab-member/zrr-application.md'
    - 'FEMTO registration procedure' : 'becoming-a-lab-member/lab-registration-procedure.md'
    - 'Important lab accounts' : 'becoming-a-lab-member/important-lab-accounts.md'
    - 'Skills updating': 'becoming-a-lab-member/skills-updating.md'
    - 'List of useful web services': 'becoming-a-lab-member/femto-st-web-services.md'

  - 'Being a lab member' : 
    - 'Roles and expectations': 'being-a-lab-member/roles-and-expectations.md'
    - 'How We Do Things': 
      - 'Time management' : 'being-a-lab-member/how-we-do-things/time-management.md'
      - 'Communication' : 'being-a-lab-member/how-we-do-things/communication.md'
      - 'Printing' : 'being-a-lab-member/how-we-do-things/printing.md'
      - 'Setting up for zoom or café neuro' : 'being-a-lab-member/how-we-do-things/setting-a-zoom-talk.md'
      - 'Life in the lab': 'being-a-lab-member/how-we-do-things/life-in-the-lab.md'
      - 'Taking guests' : 'being-a-lab-member/how-we-do-things/taking-guests.md'
    - 'Maintaining Health and Safety': 
      - 'Health & Safety' : 'being-a-lab-member/maintaining-health-and-safety/health-and-safety.md'
      - 'Caring about Happy Lab Life': 'being-a-lab-member/maintaining-health-and-safety/caring-about-happy-lab-life.md'
    - 'Leaving the Lab' :
      - 'Who to contact and when' : 'being-a-lab-member/leaving-the-lab/who-to-contact-and-when.md'
      - 'Update/Revoke Access' : 'being-a-lab-member/leaving-the-lab/update-revoke-access.md'
      - 'Requesting Letters of Recommendation' : 'being-a-lab-member/leaving-the-lab/requesting-letters-of-recommendation.md'
      - 'Future steps' : 'being-a-lab-member/leaving-the-lab/future-steps.md'
      - 'Keeping contact with ex-members' : 'being-a-lab-member/leaving-the-lab/keeping-contact-with-ex-members.md'
  - 'Running a study': 
    - 'Run a group behavioural study' : 'running-a-study/run-a-group-behavioural-study.md'
    - 'Run an online study': 'running-a-study/run-an-online-study.md'
    - 'Run an EEG study in the lab': 'running-a-study/run-an-EEG-study.md'

